spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rrhh_system?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${password}
    hikari:
      maximum-pool-size: 10         # Número máximo de conexiones en el pool
      minimum-idle: 5               # Mínimo de conexiones inactivas
      idle-timeout: 600000          # Tiempo (ms) antes de cerrar una conexión inactiva
      max-lifetime: 1800000         # Tiempo máximo de vida (ms) de una conexión
      connection-timeout: 30000     # Tiempo de espera para obtener una conexión
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

security:
  jwt:
    secret: cHJ1ZWJhLWRlbW8tZnJhbmtsaW4tdXBuLXNlZ3VyaWRhZC1zcHJpbmdib290LWp3dC1wcnVlYmEtcHJ1ZWJhLXBydWViYQ== #prueba-demo-franklin-cibertec-seguridad-springboot-jwt-prueba-prueba
    access-token:
      expiration: 900000  # 15 minutes in milliseconds
    refresh-token:
      expiration: 900000  # 15 minutes in milliseconds