spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cibertec?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10         # Número máximo de conexiones en el pool
      minimum-idle: 5               # Mínimo de conexiones inactivas
      idle-timeout: 600000          # Tiempo (ms) antes de cerrar una conexión inactiva
      max-lifetime: 1800000         # Tiempo máximo de vida (ms) de una conexión
      connection-timeout: 30000     # Tiempo de espera para obtener una conexión
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20                 # Agrupa hasta 20 operaciones en lote (inserciones/actualizaciones)
        order_inserts: true              # Ordena las inserciones para optimizar el rendimiento del batch
        order_updates: true              # Ordena las actualizaciones para mejorar el uso del batch
